# -*- coding: utf-8 -*-
"""Unit-3: .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sfq_g53fYKZFnpupbwOxIphaiuO2fUTm
"""

import numpy as np

# Create array
arr = np.array([4, 7, 2, 9, 2, 7, 5, 9, 2])
print("Array:", arr)

# Define value
value = 5

# Find elements greater than and less than value
greater_than_value = arr[arr > value]
less_than_value = arr[arr < value]

print("\nNumbers greater than", value, ":", greater_than_value)
print("Numbers less than", value, ":", less_than_value)

# Find max and min values and their indices
max_value = np.max(arr)
min_value = np.min(arr)
max_index = np.argmax(arr)
min_index = np.argmin(arr)

print("\nMaximum Value:", max_value)
print("Minimum Value:", min_value)
print("Index of Maximum Value:", max_index)
print("Index of Minimum Value:", min_index)

# Frequency count using bincount and unique
count_values = np.bincount(arr)
unique_values, counts = np.unique(arr, return_counts=True)

print("\nFrequency count using bincount:", count_values)
print("Unique values:", unique_values)
print("Counts of unique values:", counts)

