# -*- coding: utf-8 -*-
"""Unit-1: ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjsBX-2LdMSmWJgIddXtqKPmPqDvFTeT
"""

kilo_grams = float(input('Enter weight in Kg to Convert into pounds:'))
pounds = kilo_grams * 2.2
print(kilo_grams,' Kilograms =', pounds,' Pounds')

for i in range(8,90,3):
  print(i,end=" ")

text = "Hello"
char_list = list(text)
print(char_list)
# Output: ['H', 'e', 'l', 'l', 'o']

numbers = [10, 45, 2, 99, 65]
largest = max(numbers)
print("Largest number is:", largest)

class Car:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
        self.is_started = False

    def start(self):
        if not self.is_started:
            self.is_started = True
            print(f"The {self.year} {self.make} {self.model} is starting.")
        else:
            print(f"The {self.year} {self.make} {self.model} is already running.")

    def stop(self):
        if self.is_started:
            self.is_started = False
            print(f"The {self.year} {self.make} {self.model} is stopping.")
        else:
            print(f"The {self.year} {self.make} {self.model} is already stopped.")


# Create a car object
print("--- Car Class Demonstration ---")
my_car = Car("Toyota", "Camry", 2022)
print(f"My car: {my_car.make} {my

